### PR TITLE
Jdapena/spec 3982 fix first frame

### PR DESCRIPTION
**Pull request by jdapena**

### CODE REVIEW

**Comment by mv0** [comment]
Did a build with this on top, but I'm not seeing any distinguishable outcome out of it (on r-car). @jdapena should there be noticeable effects from this MR?

**Comment by jdapena** [comment]
> Did a build with this on top, but I'm not seeing any distinguishable outcome out of it (on r-car). @jdapena should there be noticeable effects from this MR?

It is a bit subtle. It delays first swap to when WAM considers there is a first meaningful frame. This should reduce the chances to see a white screen on launching new applications. The way to test this is launching HTML5 HVAC. Though, the application is showing a relayout after first meaningful paint because of not adding an early image size determination, so it will still show a small flicker.

**Comment by mv0** [comment]
Yeah, I'm seeing that re-flowing happening, but I'm not sure if that's what we're after. It does seem to be a little bit noticeable than without it, so IDK if you feel like this helps go right ahead and merge it.

I've also had a look over the wayland protocol when launching webapps-hvac, and the client *does* seem to use the correct dimensions, it never attempts to use a different buffer, it acks the correct dimensions from the beginning, as in, it creates a buffer with the correct dimensions, and uses that, so at this point I don't think re-flowing is actually related to resizing.

Further more I've attempt to use Google Chrome 101.0.4951.15 beta with --kiosk --start-fullscreen --icongnito args to try to see if that really happens differently and I can actually the same outcome, there a frame or two being displayed as grey background, after which the pages get display (happens pretty fast). Haven't really studied the protocol, and it does seem to be a bit different, but it's out of scope at this point imo. If I remove --icognito I get a white background instead for a a couple of frames. For AGL, initially I was seeing a white background when starting up, but with latest update (marlin) this changed to grey (well not sure if this information helps or not) -- don't think we actually running with incognito mode or smt. 

Yeah, and it seems to happen to both launcher and hvac (I mean starting them up). Think for the time being we're going to need to live with it, as seem to be happening, well by default.

**Comment by jdapena** [comment]
> Yeah, I'm seeing that re-flowing happening, but I'm not sure if that's what we're after. It does seem to be a little bit noticeable than without it, so IDK if you feel like this helps go right ahead and merge it.

Yup, in the end this is a change that comes from upstream and will be available in the future. So actually landing this has only temporal delta impact.

> 
> I've also had a look over the wayland protocol when launching webapps-hvac, and the client _does_ seem to use the correct dimensions, it never attempts to use a different buffer, it acks the correct dimensions from the beginning, as in, it creates a buffer with the correct dimensions, and uses that, so at this point I don't think re-flowing is actually related to resizing.

No, it is actually web page fault, as it uses a layout that depends on images size, but the size is not set anywhere, so it needs to decode the images to find where to paint stuff. It should be possible to avoid relayout by just modifying the web page to know in advance the size of the images.

I am going to land the PR. Thanks for the review!

**Pull request merged**
